# mnemospark

mnemospark is an OpenClaw plugin for storage workflow operations with wallet-based x402 USDC payments.

It focuses on:

- `/wallet` for wallet status and export
- `/cloud` for storage workflow commands (backup, price-storage, upload, ls, download, delete)
- A local proxy that forwards `/mnemospark/*` storage endpoints to the mnemospark backend with wallet-proof signing

---

## Quick start

```bash
# Install plugin (from OpenClaw)
openclaw plugins install mnemospark

# (Optional) run standalone install to create or reuse a wallet
npx mnemospark install --standard

# (Optional) set wallet key explicitly; if omitted, mnemospark auto-generates one
export BLOCKRUN_WALLET_KEY=0x...

# (Optional) point to a custom mnemospark backend API base URL
export MNEMOSPARK_BACKEND_API_BASE_URL=https://your-backend.example.com

# Start OpenClaw gateway (starts mnemospark proxy in gateway mode)
openclaw gateway start
```

In OpenClaw:

- `/wallet` to view wallet address and balance
- `/wallet export` to back up your private key
- `/cloud help` to view storage workflow commands

---

## Configuration

- **Directory layout:**
  - Base directory: `~/.openclaw/mnemospark`
  - Logs and object log: `~/.openclaw/mnemospark/object.log`
  - Wallet directory: `~/.openclaw/mnemospark/wallet`
  - Wallet key: `~/.openclaw/mnemospark/wallet/wallet.key` (or `~/.openclaw/blockrun/wallet.key` when reusing a legacy Blockrun wallet)
  - Backup archives: `~/.openclaw/mnemospark/backup`
- **Wallet key:** `BLOCKRUN_WALLET_KEY` (optional). If not provided, mnemospark auto-generates a wallet and stores it under `~/.openclaw/mnemospark/wallet/wallet.key`.
- **Backend base URL:** `MNEMOSPARK_BACKEND_API_BASE_URL` (optional if default is acceptable).
- **No backend API key:** do not set `MNEMOSPARK_BACKEND_API_KEY` or `x-api-key`. Backend authentication uses wallet-proof signatures generated by the proxy.

Install flows:

- **Default install:** `npx mnemospark install --default` creates a new Base wallet for mnemospark under `~/.openclaw/mnemospark/wallet/wallet.key` (chmod 600).
- **Standard install:** `npx mnemospark install --standard` checks for an existing `~/.openclaw/blockrun/wallet.key` and, if present, offers to reuse it for mnemospark; otherwise it behaves like the default install.

---

## Workflow and product references

- [mnemospark full workflow](./.company/mnemospark_full_workflow.md)
- [mnemospark PRD](./.company/mnemospark_PRD.md)
- [mnemospark backend API spec](./.company/mnemospark_backend_api_spec.md)

---

## Python examples (uv)

Python tooling and examples use [uv](https://docs.astral.sh/uv/) for dependency management. From the repo root:

```bash
# Install uv (macOS/Linux): curl -LsSf https://astral.sh/uv/install.sh | sh
uv sync --extra bcm-pricing
source .venv/bin/activate      # or on Windows: .venv\Scripts\activate
python examples/s3_storage_cost_estimate.py --gb 100
python examples/data_transfer_cost_estimate.py --direction in --gb 100
python examples/data_transfer_cost_estimate.py --direction out --gb 500
```

---

## License

MIT
